import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
});

const SITE_URL = "https://abs-bridge.nine-chronicles.com";
const TITLE = "WNCG Bridge — Bridge WNCG between Ethereum and Abstract";
const DESCRIPTION =
  "The official WNCG bridge. Move Wrapped NCG (WNCG) between Ethereum (L1) and Abstract (L2), a ZK Stack chain — deposits in ~3 minutes, withdrawals finalized on L1 via the ZK Stack Bridgehub. Connect with RainbowKit and bridge in two clicks.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: TITLE,
    template: "%s — WNCG Bridge",
  },
  description: DESCRIPTION,
  applicationName: "WNCG Bridge",
  keywords: [
    "WNCG bridge",
    "Wrapped NCG",
    "WNCG",
    "Nine Chronicles",
    "NCG",
    "Abstract bridge",
    "Ethereum Abstract bridge",
    "ZK Stack bridge",
    "bridge WNCG to Abstract",
    "L1 L2 bridge",
    "zkSync Abstract",
    "Planetarium Labs",
  ],
  authors: [{ name: "Planetarium Labs", url: "https://www.planetariumlabs.com/" }],
  creator: "Planetarium Labs",
  publisher: "Planetarium Labs",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: "WNCG Bridge",
    title: TITLE,
    description: DESCRIPTION,
    // OG image is generated by app/opengraph-image.tsx (@vercel/og) and auto-attached.
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
    // Twitter image is auto-derived from opengraph-image.tsx.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/assets/wncg-icon.png",
    apple: "/assets/wncg-icon.png",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#0A0908",
};

// Structured data for both classic rich results and GEO (AI-search citation).
// The FAQPage entries are written "answer-first" with concrete numbers so engines like
// Perplexity / ChatGPT / Google AI Overview can extract and cite them directly.
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": `${SITE_URL}/#org`,
      name: "Planetarium Labs",
      url: "https://www.planetariumlabs.com/",
      sameAs: [
        "https://nine-chronicles.com/",
        "https://github.com/planetarium",
        "https://x.com/NineChronicles",
      ],
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      url: SITE_URL,
      name: "WNCG Bridge",
      inLanguage: "en",
      publisher: { "@id": `${SITE_URL}/#org` },
    },
    {
      "@type": "SoftwareApplication",
      "@id": `${SITE_URL}/#app`,
      name: "WNCG Bridge",
      applicationCategory: "FinanceApplication",
      applicationSubCategory: "Cross-chain bridge",
      operatingSystem: "Web",
      url: SITE_URL,
      description: DESCRIPTION,
      browserRequirements: "Requires an EVM wallet such as MetaMask or Rabby.",
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
      publisher: { "@id": `${SITE_URL}/#org` },
      featureList: [
        "Deposit WNCG from Ethereum (L1) to Abstract (L2)",
        "Withdraw WNCG from Abstract back to Ethereum",
        "Claim finalized L1 withdrawals",
        "RainbowKit wallet connection",
      ],
    },
    {
      "@type": "FAQPage",
      "@id": `${SITE_URL}/#faq`,
      mainEntity: [
        {
          "@type": "Question",
          name: "What is the WNCG bridge?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "The WNCG bridge is a web app that moves Wrapped NCG (WNCG), an 18-decimal ERC-20 token, between Ethereum (L1) and Abstract (L2), a ZK Stack chain. Deposits lock WNCG on Ethereum and mint it on Abstract; withdrawals burn it on Abstract and unlock it on Ethereum, all routed through the ZK Stack Bridgehub.",
          },
        },
        {
          "@type": "Question",
          name: "How long does it take to bridge WNCG to Abstract?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Depositing WNCG from Ethereum to Abstract takes roughly a few minutes — funds mint on Abstract once the L1 transaction is finalized. A first-time deposit requires two wallet signatures: an ERC-20 approve, then the deposit.",
          },
        },
        {
          "@type": "Question",
          name: "How long does a WNCG withdrawal from Abstract to Ethereum take?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Withdrawals from Abstract (L2) to Ethereum (L1) follow ZK Stack finality: the batch is committed and proven on Ethereum, with a security delay, taking about 3 hours and up to roughly 24 hours when the network is busy. After it matures you claim it on L1 in a separate transaction to receive your WNCG.",
          },
        },
        {
          "@type": "Question",
          name: "Which wallets can I use with the WNCG bridge?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "The bridge uses RainbowKit, so any EVM wallet works — MetaMask, Rabby, Coinbase Wallet, Rainbow, and WalletConnect-compatible mobile wallets.",
          },
        },
        {
          "@type": "Question",
          name: "What are the WNCG token contract addresses?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "WNCG on Ethereum (L1) is 0xf203Ca1769ca8e9e8FE1DA9D147DB68B6c919817. WNCG on Abstract (L2, chain ID 2741) is 0x3a058F406654B908a60cBE296faC03C7bF1c6769. Both are 18-decimal ERC-20 tokens.",
          },
        },
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${inter.variable} ${jetbrainsMono.variable}`}>
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
